In [ ]:
from ...pactor.python.actor import IActor

In [ ]:
import requests
response = requests.get('https://www.google.com')
print(response.text)

In [26]:
...

Ellipsis

In [33]:
print(type(Ellipsis))
print(type(...))
print(Ellipsis == ...)

<class 'ellipsis'>
<class 'ellipsis'>
True
Ellipsis


In [25]:
import numpy as np

v = tuple([slice(None, None), slice(None, 2), None])
v = tuple([slice(None, None), slice(None, 2), np.newaxis])
A = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print(A[v])

[[[1]
  [2]]

 [[4]
  [5]]]


In [36]:
import numpy as np

v = tuple([slice(None, None), slice(None, 2), None])
v = tuple([slice(1, 2)])
A = np.array([1, 2, 3, 4, 5, 6])
A[v]
A[1]

2

In [45]:
from gymize.proto.space_pb2 import TensorProto
import numpy as np

tensor = TensorProto()
tensor.shape.extend([1, 2, 3])
tensor.float_array.extend([1.0, 2.0, 3.0, 4.0, 5.0, 6.0])

np.array(tensor.float_array, dtype=np.int32).reshape(tensor.shape)

array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)

In [51]:
import numpy as np
import collections

arr = [1, 2, 3, 4, 5, 6]
dictionary = {'a': 1, 'b': 2, 'c': 3}
nd = np.array([1, 2, 3, 4, 5])
tup = (1, 2, 3, 4, 5,)

print(isinstance(arr, collections.abc.Iterable))
print(isinstance(arr, collections.abc.Sequence))
print(isinstance(arr, collections.abc.Mapping))
print(isinstance(dictionary, collections.abc.Iterable))
print(isinstance(dictionary, collections.abc.Sequence))
print(isinstance(dictionary, collections.abc.Mapping))
print(isinstance(nd, collections.abc.Iterable))
print(isinstance(nd, collections.abc.Sequence))
print(isinstance(nd, collections.abc.Mapping))
print(isinstance(tup, collections.abc.Iterable))
print(isinstance(tup, collections.abc.Sequence))
print(isinstance(tup, collections.abc.Mapping))

True
True
False
True
False
True
True
False
False
True
True
False


In [52]:
import numpy as np

nd = np.zeros((540, 960, 3))
print(nd.shape)
ndt = nd.transpose([1, 0, 2])
print(ndt.shape)

(540, 960, 3)
(960, 540, 3)


In [59]:
import numpy as np

np.dtype(np.int8).str

'|i1'

In [60]:
import numpy as np
tuple(np.array([1, 2, 3]))

(1, 2, 3)

In [9]:
import numpy as np

i = int(2)
np.isscalar(i)
type(4) == np.int64
np.issubdtype(type(4), np.integer)
np.issubdtype(type(4.0), np.floating)
np.issubdtype(type(True), np.bool_)

True

In [1]:
arr = [1, 2, 3, 4, 5, 6]

arr[2:4] = [7, 8, 9]
arr

[1, 2, 7, 8, 9, 5, 6]

In [13]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
np.vstack([arr, np.array([5, 6])])


array([[1, 2],
       [3, 4],
       [5, 6]])